name: 3d-retr
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.4.13=h06a4308_1
  - certifi=2020.12.5=py36h06a4308_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - dataclasses=0.8=pyh4f3eec9_6
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.2.0=h06a4308_610
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libidn2=2.3.0=h27cfd23_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - lz4-c=1.9.3=h2531618_0
  - mkl=2020.2=256
  - mkl-service=2.3.0=py36he8ac12f_0
  - mkl_fft=1.3.0=py36h54f3939_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.2=hbbd107a_1
  - numpy=1.19.2=py36h54aff64_0
  - numpy-base=1.19.2=py36hfa32c7d_0
  - olefile=0.46=py36_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1k=h27cfd23_0
  - pillow=8.2.0=py36he98fc37_0
  - pip=21.0.1=py36h06a4308_0
  - python=3.6.13=hdb3f193_0
  - pytorch=1.8.1=py3.6_cuda10.1_cudnn7.6.3_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.15.0=py36h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - torchaudio=0.8.1=py36
  - torchvision=0.9.1=py36_cu101
  - typing_extensions=3.7.4.3=pyha847dfd_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.12.0
    - aiohttp==3.7.4.post0
    - alembic==1.4.1
    - async-timeout==3.0.1
    - attrs==21.2.0
    - axial-positional-embedding==0.2.1
    - cachetools==4.2.2
    - chardet==4.0.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - databricks-cli==0.14.3
    - dill==0.3.3
    - docker==5.0.0
    - einops==0.3.0
    - entrypoints==0.3
    - filelock==3.0.12
    - flask==1.1.2
    - fsspec==2021.4.0
    - ftfy==6.0.1
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.14
    - google-auth==1.30.0
    - google-auth-oauthlib==0.4.4
    - greenlet==1.1.0
    - grpcio==1.37.1
    - gunicorn==20.1.0
    - huggingface-hub==0.0.8
    - idna==2.10
    - idna-ssl==1.1.0
    - imagesize==1.2.0
    - importlib-metadata==4.0.1
    - itsdangerous==1.1.0
    - jinja2==2.11.3
    - joblib==1.0.1
    - kiwisolver==1.3.1
    - mako==1.1.4
    - markdown==3.3.4
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mlflow==1.17.0
    - multidict==5.1.0
    - ninja==1.10.0.post2
    - oauthlib==3.1.0
    - opencv-python==4.5.2.52
    - packaging==20.9
    - pandas==1.1.5
    - prometheus-client==0.10.1
    - prometheus-flask-exporter==0.18.2
    - protobuf==3.16.0
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.0
    - pynrrd==0.4.2
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - pytorch-lightning==1.3.3
    - pytz==2021.1
    - pyyaml==5.4.1
    - querystring-parser==1.2.4
    - regex==2021.4.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - sacremoses==0.0.45
    - scipy==1.5.4
    - smmap==4.0.0
    - sqlalchemy==1.4.14
    - sqlparse==0.4.1
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - tensorboardx==1.8
    - timm==0.4.5
    - tokenizers==0.10.3
    - torchmetrics==0.3.1
    - tqdm==4.60.0
    - transformers==4.6.1
    - trimesh==3.9.16
    - urllib3==1.26.4
    - vector-quantize-pytorch==0.1.0
    - wcwidth==0.2.5
    - websocket-client==0.59.0
    - werkzeug==1.0.1
    - yarl==1.6.3
    - zipp==3.4.1
